import Head from 'next/head'
import styles from "@/styles/Home.module.css"

export default function Home() {
  const container = styles["container"];
  const main = styles["main"];
  const title = styles["title"];
  const description = styles["description"];
  const grid = styles["grid"];
  const card = styles["card"];
  const code = styles["code"];
  const footer = styles["footer"];
  const logo = styles["logo"];

  return (
    <div className={container}>
      <Head>
        <title>Portal de Mantenimiento de Gastos de Cobranza</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/bb-favicon.jpg" />
      </Head>

      <main className={main}>
        <h1 className={title}>
          Bienvenidos al portal de mantenimiento de Gastos de Cobranza
        </h1>

        <p className={description}>
          Seleccione una de las opciones disponibles en el menú lateral para continuar
        </p>

      </main>

      <footer className={footer}>
      </footer>
    </div>
  )
}
